name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      # image: 'ubuntu:20.04' # can also use this to test
      image: 'tfsec/tfsec'
      credentials:
         username: ${{ secrets.DOCKERHUB_TOKEN }}
         password: ${{ secrets.DOCKERHUB_USERNAME }}
        