name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: tfsec:latest
    steps:
      - name: scan local terraform respository
        run: tfsec