name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: tfsec/tfsec:v1.13.2-arm64v8
    steps:
    - name: display version
      uses: tfsec --versio
        